spring:
    web:
        resources:
            static-locations[0]: "file:src/main/resources/static/"
            static-locations[1]: "classpath:/static/"
    devtools:
        livereload:
            enabled: true
        restart:
            additional-paths: "file:src/main/resources/static/"
